### ISSUE TITLE
Build fails with NAG compiler

### ISSUE THREAD

**Issue by awvwgk** [libmbd/libmbd#32] opened 2021-12-03 14:16 UTC
Maybe an argument mismatch

```
Error: external/mbd/origin/src/mbd_geom.F90, line 249: Inconsistent data type CHARACTER (previously INTEGER) for argument 1 in reference to MPI_BCAST
Error: external/mbd/origin/src/mbd_geom.F90, line 252: Inconsistent data type CHARACTER (previously INTEGER) for argument 1 in reference to MPI_BCAST
```

**Comment by awvwgk** [comment] 2021-12-03 15:47
Caused from the usage of `MPI_BCAST` as `external` procedure with different datatypes.
https://github.com/libmbd/libmbd/blob/f6494a46c6cc39ff5325d56ef38af11bb4fd651f/src/mbd_geom.F90#L248-L254

Possible fixes are using the `-mismatch` option or by using the newer `mpi_f08` module with type information rather than `external` declarations.

cc @aradi

**Comment by jhrmnn** [comment] 2021-12-03 15:51
Yeah, I know about this. I've been using the `-mismatch` option with Gfortran>=10 so far. The only reason is that I didn't want to spend the time to look into how to use `mpi_f90` and then making sure that Libmbd also works with older compilers that probably don't support it.

**Comment by aradi** [comment] 2021-12-03 19:38
It is less the compiler, but the MPI-framework, which is the problem. It typically happens with MPICH. And indeed, older (but still used) MPICH versions do not have the `mpi_f08` module, so I won't recommend it yet. In #33, I have a possible solution (the same we use in MPIFX). It also fixes the incorrect linking order of ScaLAPACK and LAPACK, which will hit you, if you build statically. (When one uses targets for linking dependencies, dependency relations between targets can be defined, so that the order they appear is irrelevant. When using variables instead, the order unfortunately matters)

**Comment by jhrmnn** [comment] 2021-12-03 20:07
I guess at some point I should just switch Libmbd to all your smart wrappers :) Thanks for the PR, merged.

I have already a commit prepared that switches everything to targets, like here https://github.com/libmbd/libmbd/commit/c58aaef02e1ae8b60362a01d7759711cd3a76aca#diff-148715d6ea0c0ea0a346af3f6bd610d010d490eca35ac6a9b408748f7ca9e3f4. I assume that then the order shouldn't matter?

**Closed** 2021-12-03 20:07 UTC

**Comment by aradi** [comment] 2021-12-03 20:19
Dependency of the targets on each other can also be defined via `target_link_libraries()`. If those are correctly defined, then the order they appear in a `target_link_libraries()` call for a library or an executable should not matter. The only caveat is, that some of CMakes built-in finders (especially in older CMakes < 3.20) are broken and do not export the targets correctly. So make sure, you test the approach with the oldest CMake version you are willing to support...

**Comment by jhrmnn** [comment] 2021-12-13 13:59
> Caused from the usage of `MPI_BCAST` as `external` procedure with different datatypes.

Actually, this is specific to the MPI framework that you use rather than a compiler, right? AFAIK, OpenMPI declares `MPI_BCAST` as a generic interface for all the possible types, so this is not an issue then, and GFortran 10 would work just fine in fact. Could this be even considered an issue of the MPI framework, not of Libmbd?

**Comment by aradi** [comment] 2021-12-13 15:39
> > Caused from the usage of `MPI_BCAST` as `external` procedure with different datatypes.
> 
> Actually, this is specific to the MPI framework that you use rather than a compiler, right? AFAIK, OpenMPI declares `MPI_BCAST` as a generic interface for all the possible types, so this is not an issue then, and GFortran 10 would work just fine in fact. Could this be even considered an issue of the MPI framework, not of Libmbd?

Yes, it is indeed caused by the way, how mpich handles the F90 interface. OpenMPI does it much better and, therefore, no problems arise there. You could try to get the mpich-people fix it, but chances are high that they won't, especially because Fortran 2008 is the first version of the standard, which makes a really standard conforming MPI-interface possible. But that interface is implemented in the `mpi_f08` module, which newer mpich versions ship. So, actually, we all should at some point change to that, instead of experimenting with the f90-interface, which is always broken in some way. (Unfortunately, only recent mpich versions have that module, and I don't know, how good it works...)

**Comment by jhrmnn** [comment] 2021-12-13 15:46
I see. So then the current detection of when to pass the mismatch flag isn't really correct, because it doesn't check for the MPI vendor. I'm not sure Libmbd should be actually attempting that detection, but I'll leave it in for now.

**Comment by aradi** [comment] 2021-12-13 15:50
I would not go for MPI-vendor detection either. Currently, I'd just allow mismatch whenever MPI is involved. Once you turn to `mpi_f08`, you should be able to disallow it globally again.

**Comment by jhrmnn** [comment] 2021-12-13 19:10
Turned out it was pretty easy to support `mpi_f08` as well #38. Could you use that in DFTB+ so I could remove the mismatch logic?

**Comment by aradi** [comment] 2021-12-14 07:46
Yes, that makes sense, I will tackle that (dftbplus/mpifx#34), but first I want to finish the Conda-packaging with all our dependencies for the current release...

**Comment by jhrmnn** [comment] 2021-12-15 09:33
In case you ever hit this problem: Even when `-fallow-argument-mismatch` is used with Gfortran, `-pedantic` actually upgrades the warning back to an error, and it seems the Gfortran developers want it like that:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102145
